<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5VYkGc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5VYkGc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS5VYkGc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS5VYkGc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS5VYkGc\App_KernelDevDebugContainer([
    'container.build_hash' => 'S5VYkGc',
    'container.build_id' => 'fa76e978',
    'container.build_time' => 1658351836,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS5VYkGc');
