<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPXxhdqv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPXxhdqv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPXxhdqv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPXxhdqv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPXxhdqv\App_KernelDevDebugContainer([
    'container.build_hash' => 'PXxhdqv',
    'container.build_id' => 'addf9ff5',
    'container.build_time' => 1658353642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPXxhdqv');
